# Server Configuration
server:
  undertow:
    worker-threads: 20

app:
  thread.async:
    corePoolSize: 20
    maxPoolSize: 300
    queueCapacity: 600

spring:
  mvc:
    async:
      request-timeout: -1

info:
  app:
    name: Sample-DeferredResult-Spring
    description: Application of Sample to use DeferredResult
    version: 0.0.1